// Code generated by go-swagger; DO NOT EDIT.

// Package restapi Tournament API
//
//	API for tournament management and participation
//	Schemes:
//	  http
//	  https
//	Host: api.example.com
//	BasePath: /
//	Version: 1.0.0
//
//	Consumes:
//	  - application/json
//
//	Produces:
//	  - application/json
//
// swagger:meta
package restapi
