// Code generated by go-swagger; DO NOT EDIT.

package restapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
)

var (
	// SwaggerJSON embedded version of the swagger document used at generation time
	SwaggerJSON json.RawMessage
	// FlatSwaggerJSON embedded flattened version of the swagger document used at generation time
	FlatSwaggerJSON json.RawMessage
)

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "schemes": [
    "https",
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "description": "API for tournament management and participation",
    "title": "Tournament API",
    "version": "1.0.0"
  },
  "host": "api.example.com",
  "basePath": "/",
  "paths": {
    "/login": {
      "post": {
        "tags": [
          "auth"
        ],
        "summary": "Authenticate user",
        "parameters": [
          {
            "name": "credentials",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/LoginRequest"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Successful authentication",
            "schema": {
              "$ref": "#/definitions/LoginResponse"
            }
          },
          "400": {
            "$ref": "#/responses/BadRequest"
          }
        }
      }
    },
    "/tournaments": {
      "get": {
        "tags": [
          "tournaments"
        ],
        "summary": "Get active tournament and leaderboard",
        "responses": {
          "200": {
            "description": "Tournament leaderboard",
            "schema": {
              "$ref": "#/definitions/TournamentOverview"
            }
          },
          "401": {
            "$ref": "#/responses/Unauthorized"
          },
          "403": {
            "$ref": "#/responses/Forbidden"
          }
        }
      }
    },
    "/tournaments/{tournamentId}/": {
      "get": {
        "tags": [
          "tournaments"
        ],
        "summary": "Get tournament details",
        "parameters": [
          {
            "type": "integer",
            "name": "tournamentId",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Tournament details",
            "schema": {
              "$ref": "#/definitions/Tournament"
            }
          },
          "401": {
            "$ref": "#/responses/Unauthorized"
          },
          "403": {
            "$ref": "#/responses/Forbidden"
          }
        }
      }
    },
    "/tournaments/{tournamentId}/tasks/{taskId}": {
      "get": {
        "tags": [
          "tasks"
        ],
        "summary": "Get task details",
        "parameters": [
          {
            "type": "integer",
            "name": "tournamentId",
            "in": "path",
            "required": true
          },
          {
            "type": "integer",
            "name": "taskId",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Team task details",
            "schema": {
              "$ref": "#/definitions/TeamTask"
            }
          },
          "401": {
            "$ref": "#/responses/Unauthorized"
          },
          "403": {
            "$ref": "#/responses/Forbidden"
          },
          "404": {
            "$ref": "#/responses/NotFound"
          }
        }
      },
      "patch": {
        "tags": [
          "tasks"
        ],
        "summary": "Submit answer for task",
        "parameters": [
          {
            "type": "integer",
            "name": "tournamentId",
            "in": "path",
            "required": true
          },
          {
            "type": "integer",
            "name": "taskId",
            "in": "path",
            "required": true
          },
          {
            "name": "answer",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/TaskAnswerRequest"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Answer processed",
            "schema": {
              "$ref": "#/definitions/TaskAnswerResponse"
            }
          },
          "400": {
            "$ref": "#/responses/BadRequest"
          },
          "401": {
            "$ref": "#/responses/Unauthorized"
          },
          "403": {
            "$ref": "#/responses/Forbidden"
          },
          "404": {
            "$ref": "#/responses/NotFound"
          },
          "409": {
            "$ref": "#/responses/TooManyAttempts"
          }
        }
      }
    },
    "/tournaments/{tournamentId}/tasks/{taskId}/hints/{hintId}": {
      "get": {
        "tags": [
          "hints"
        ],
        "summary": "Get hint details",
        "parameters": [
          {
            "type": "integer",
            "name": "tournamentId",
            "in": "path",
            "required": true
          },
          {
            "type": "integer",
            "name": "taskId",
            "in": "path",
            "required": true
          },
          {
            "type": "integer",
            "name": "hintId",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Hint details",
            "schema": {
              "$ref": "#/definitions/Hint"
            }
          },
          "401": {
            "$ref": "#/responses/Unauthorized"
          },
          "403": {
            "$ref": "#/responses/Forbidden"
          },
          "404": {
            "$ref": "#/responses/NotFound"
          }
        }
      },
      "patch": {
        "tags": [
          "hints"
        ],
        "summary": "Open hint for task",
        "parameters": [
          {
            "type": "integer",
            "name": "tournamentId",
            "in": "path",
            "required": true
          },
          {
            "type": "integer",
            "name": "taskId",
            "in": "path",
            "required": true
          },
          {
            "type": "integer",
            "name": "hintId",
            "in": "path",
            "required": true
          },
          {
            "name": "status",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/HintOpenRequest"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Hint opened",
            "schema": {
              "$ref": "#/definitions/Hint"
            }
          },
          "401": {
            "$ref": "#/responses/Unauthorized"
          },
          "403": {
            "$ref": "#/responses/Forbidden"
          },
          "404": {
            "$ref": "#/responses/NotFound"
          }
        }
      }
    }
  },
  "definitions": {
    "Attempt": {
      "$ref": "components/schemas/Attempt.yaml"
    },
    "Error": {
      "$ref": "components/schemas/Error.yaml"
    },
    "Hint": {
      "$ref": "components/schemas/Hint.yaml"
    },
    "HintOpenRequest": {
      "$ref": "components/schemas/HintOpenRequest.yaml"
    },
    "LoginRequest": {
      "$ref": "components/schemas/LoginRequest.yaml"
    },
    "LoginResponse": {
      "$ref": "components/schemas/LoginResponse.yaml"
    },
    "Task": {
      "$ref": "components/schemas/Task.yaml"
    },
    "TaskAnswerRequest": {
      "$ref": "components/schemas/TaskAnswerRequest.yaml"
    },
    "TaskAnswerResponse": {
      "$ref": "components/schemas/TaskAnswerResponse.yaml"
    },
    "TeamOverview": {
      "$ref": "components/schemas/TeamOverview.yaml"
    },
    "TeamTask": {
      "$ref": "components/schemas/TeamTask.yaml"
    },
    "TeamTaskOverview": {
      "$ref": "components/schemas/TeamTaskOverview.yaml"
    },
    "Tournament": {
      "$ref": "components/schemas/Tournament.yaml"
    },
    "TournamentOverview": {
      "$ref": "components/schemas/TournamentOverview.yaml"
    }
  },
  "responses": {
    "BadRequest": {
      "description": "Bad request",
      "schema": {
        "$ref": "#/definitions/Error"
      }
    },
    "Forbidden": {
      "description": "Forbidden",
      "schema": {
        "$ref": "#/definitions/Error"
      }
    },
    "NotFound": {
      "description": "Resource not found",
      "schema": {
        "$ref": "#/definitions/Error"
      }
    },
    "TooManyAttempts": {
      "description": "Maximum attempts exceeded",
      "schema": {
        "$ref": "#/definitions/Error"
      }
    },
    "Unauthorized": {
      "description": "Unauthorized",
      "schema": {
        "$ref": "#/definitions/Error"
      }
    }
  },
  "tags": [
    {
      "description": "Authentication and authorization",
      "name": "auth"
    },
    {
      "description": "Tournament operations",
      "name": "tournaments"
    },
    {
      "description": "Task operations",
      "name": "tasks"
    },
    {
      "description": "Hint operations",
      "name": "hints"
    }
  ]
}`))
	FlatSwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "schemes": [
    "https",
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "description": "API for tournament management and participation",
    "title": "Tournament API",
    "version": "1.0.0"
  },
  "host": "api.example.com",
  "basePath": "/",
  "paths": {
    "/login": {
      "post": {
        "tags": [
          "auth"
        ],
        "summary": "Authenticate user",
        "parameters": [
          {
            "name": "credentials",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/LoginRequest"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Successful authentication",
            "schema": {
              "$ref": "#/definitions/LoginResponse"
            }
          },
          "400": {
            "description": "Bad request",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    },
    "/tournaments": {
      "get": {
        "tags": [
          "tournaments"
        ],
        "summary": "Get active tournament and leaderboard",
        "responses": {
          "200": {
            "description": "Tournament leaderboard",
            "schema": {
              "$ref": "#/definitions/TournamentOverview"
            }
          },
          "401": {
            "description": "Unauthorized",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "403": {
            "description": "Forbidden",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    },
    "/tournaments/{tournamentId}/": {
      "get": {
        "tags": [
          "tournaments"
        ],
        "summary": "Get tournament details",
        "parameters": [
          {
            "type": "integer",
            "name": "tournamentId",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Tournament details",
            "schema": {
              "$ref": "#/definitions/Tournament"
            }
          },
          "401": {
            "description": "Unauthorized",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "403": {
            "description": "Forbidden",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    },
    "/tournaments/{tournamentId}/tasks/{taskId}": {
      "get": {
        "tags": [
          "tasks"
        ],
        "summary": "Get task details",
        "parameters": [
          {
            "type": "integer",
            "name": "tournamentId",
            "in": "path",
            "required": true
          },
          {
            "type": "integer",
            "name": "taskId",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Team task details",
            "schema": {
              "$ref": "#/definitions/TeamTask"
            }
          },
          "401": {
            "description": "Unauthorized",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "403": {
            "description": "Forbidden",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "404": {
            "description": "Resource not found",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      },
      "patch": {
        "tags": [
          "tasks"
        ],
        "summary": "Submit answer for task",
        "parameters": [
          {
            "type": "integer",
            "name": "tournamentId",
            "in": "path",
            "required": true
          },
          {
            "type": "integer",
            "name": "taskId",
            "in": "path",
            "required": true
          },
          {
            "name": "answer",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/TaskAnswerRequest"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Answer processed",
            "schema": {
              "$ref": "#/definitions/TaskAnswerResponse"
            }
          },
          "400": {
            "description": "Bad request",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "401": {
            "description": "Unauthorized",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "403": {
            "description": "Forbidden",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "404": {
            "description": "Resource not found",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "409": {
            "description": "Maximum attempts exceeded",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    },
    "/tournaments/{tournamentId}/tasks/{taskId}/hints/{hintId}": {
      "get": {
        "tags": [
          "hints"
        ],
        "summary": "Get hint details",
        "parameters": [
          {
            "type": "integer",
            "name": "tournamentId",
            "in": "path",
            "required": true
          },
          {
            "type": "integer",
            "name": "taskId",
            "in": "path",
            "required": true
          },
          {
            "type": "integer",
            "name": "hintId",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Hint details",
            "schema": {
              "$ref": "#/definitions/Hint"
            }
          },
          "401": {
            "description": "Unauthorized",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "403": {
            "description": "Forbidden",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "404": {
            "description": "Resource not found",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      },
      "patch": {
        "tags": [
          "hints"
        ],
        "summary": "Open hint for task",
        "parameters": [
          {
            "type": "integer",
            "name": "tournamentId",
            "in": "path",
            "required": true
          },
          {
            "type": "integer",
            "name": "taskId",
            "in": "path",
            "required": true
          },
          {
            "type": "integer",
            "name": "hintId",
            "in": "path",
            "required": true
          },
          {
            "name": "status",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/HintOpenRequest"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Hint opened",
            "schema": {
              "$ref": "#/definitions/Hint"
            }
          },
          "401": {
            "description": "Unauthorized",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "403": {
            "description": "Forbidden",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "404": {
            "description": "Resource not found",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "Attempt": {
      "type": "object",
      "required": [
        "id",
        "text",
        "status",
        "time"
      ],
      "properties": {
        "id": {
          "description": "Attempt identifier",
          "type": "integer"
        },
        "status": {
          "description": "Attempt status",
          "type": "string",
          "enum": [
            "pending",
            "correct",
            "incorrect"
          ]
        },
        "text": {
          "description": "Text of attempt",
          "type": "string"
        },
        "time": {
          "description": "Time of attempt",
          "type": "string",
          "format": "date-time"
        }
      }
    },
    "Error": {
      "type": "object",
      "required": [
        "code",
        "message"
      ],
      "properties": {
        "code": {
          "description": "Application-specific error code",
          "type": "integer"
        },
        "message": {
          "description": "Human readable error description",
          "type": "string"
        }
      }
    },
    "Hint": {
      "type": "object",
      "required": [
        "id",
        "status"
      ],
      "properties": {
        "id": {
          "description": "Hint identifier",
          "type": "integer"
        },
        "status": {
          "description": "Hint status",
          "type": "string",
          "enum": [
            "hidden",
            "open"
          ]
        },
        "text": {
          "description": "Hint text, omitted when status is hidden",
          "type": "string",
          "x-nullable": true
        }
      }
    },
    "HintOpenRequest": {
      "type": "object",
      "required": [
        "status"
      ],
      "properties": {
        "status": {
          "description": "Desired hint status",
          "type": "string",
          "enum": [
            "open"
          ]
        }
      }
    },
    "LoginRequest": {
      "type": "object",
      "required": [
        "login",
        "password"
      ],
      "properties": {
        "login": {
          "description": "User login",
          "type": "string",
          "minLength": 1
        },
        "password": {
          "description": "User password",
          "type": "string",
          "format": "password",
          "minLength": 1
        }
      }
    },
    "LoginResponse": {
      "type": "object",
      "required": [
        "tournament_id"
      ],
      "properties": {
        "tournament_id": {
          "description": "Identifier of available tournament",
          "type": "integer",
          "format": "int64"
        }
      }
    },
    "Task": {
      "type": "object",
      "required": [
        "id",
        "name",
        "text"
      ],
      "properties": {
        "id": {
          "description": "Task identifier",
          "type": "integer"
        },
        "name": {
          "description": "Task name",
          "type": "string"
        },
        "text": {
          "description": "Task text",
          "type": "string"
        }
      }
    },
    "TaskAnswerRequest": {
      "type": "object",
      "required": [
        "answer"
      ],
      "properties": {
        "answer": {
          "description": "User submitted answer",
          "type": "string",
          "minLength": 1
        }
      }
    },
    "TaskAnswerResponse": {
      "type": "object",
      "required": [
        "status"
      ],
      "properties": {
        "status": {
          "description": "Result of attempt",
          "type": "string",
          "enum": [
            "correct",
            "incorrect"
          ]
        }
      }
    },
    "TeamOverview": {
      "type": "object",
      "required": [
        "id",
        "name",
        "login",
        "tasks",
        "completed",
        "place",
        "penalty"
      ],
      "properties": {
        "completed": {
          "description": "Number of completed tasks",
          "type": "integer"
        },
        "id": {
          "description": "Team identifier",
          "type": "integer"
        },
        "login": {
          "description": "Login used by the team",
          "type": "string"
        },
        "name": {
          "description": "Team name",
          "type": "string"
        },
        "penalty": {
          "description": "Penalty time in seconds",
          "type": "integer"
        },
        "place": {
          "description": "Team place in tournament",
          "type": "integer"
        },
        "tasks": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/TeamTaskOverview"
          }
        }
      }
    },
    "TeamTask": {
      "type": "object",
      "required": [
        "task",
        "status",
        "attempts",
        "hints"
      ],
      "properties": {
        "attempts": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/Attempt"
          }
        },
        "hints": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/Hint"
          }
        },
        "status": {
          "description": "Task status for team",
          "type": "string",
          "enum": [
            "pending",
            "correct",
            "incorrect"
          ]
        },
        "task": {
          "$ref": "#/definitions/Task"
        }
      }
    },
    "TeamTaskOverview": {
      "type": "object",
      "required": [
        "name",
        "status"
      ],
      "properties": {
        "name": {
          "description": "Task name",
          "type": "string"
        },
        "status": {
          "description": "Task status for team",
          "type": "string",
          "enum": [
            "pending",
            "correct",
            "incorrect"
          ]
        }
      }
    },
    "Tournament": {
      "type": "object",
      "required": [
        "id",
        "name",
        "coords",
        "description",
        "tasks",
        "status"
      ],
      "properties": {
        "coords": {
          "description": "Geographic coordinates",
          "type": "string"
        },
        "description": {
          "description": "Tournament description",
          "type": "string",
          "maxLength": 300
        },
        "id": {
          "description": "Tournament identifier",
          "type": "integer"
        },
        "name": {
          "description": "Tournament name",
          "type": "string"
        },
        "status": {
          "description": "Current tournament status",
          "type": "string",
          "enum": [
            "in_progress",
            "done"
          ]
        },
        "tasks": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/TeamTask"
          }
        }
      }
    },
    "TournamentOverview": {
      "type": "object",
      "required": [
        "id",
        "name",
        "teams"
      ],
      "properties": {
        "id": {
          "description": "Tournament identifier",
          "type": "integer"
        },
        "name": {
          "description": "Tournament name",
          "type": "string"
        },
        "teams": {
          "description": "Teams ordered by tournament results",
          "type": "array",
          "items": {
            "$ref": "#/definitions/TeamOverview"
          }
        }
      }
    }
  },
  "responses": {
    "BadRequest": {
      "description": "Bad request",
      "schema": {
        "$ref": "#/definitions/Error"
      }
    },
    "Forbidden": {
      "description": "Forbidden",
      "schema": {
        "$ref": "#/definitions/Error"
      }
    },
    "NotFound": {
      "description": "Resource not found",
      "schema": {
        "$ref": "#/definitions/Error"
      }
    },
    "TooManyAttempts": {
      "description": "Maximum attempts exceeded",
      "schema": {
        "$ref": "#/definitions/Error"
      }
    },
    "Unauthorized": {
      "description": "Unauthorized",
      "schema": {
        "$ref": "#/definitions/Error"
      }
    }
  },
  "tags": [
    {
      "description": "Authentication and authorization",
      "name": "auth"
    },
    {
      "description": "Tournament operations",
      "name": "tournaments"
    },
    {
      "description": "Task operations",
      "name": "tasks"
    },
    {
      "description": "Hint operations",
      "name": "hints"
    }
  ]
}`))
}
