// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// HintOpenRequest hint open request
//
// swagger:model HintOpenRequest
type HintOpenRequest struct {

	// Desired hint status
	// Required: true
	// Enum: [open]
	Status *string `json:"status"`
}

// Validate validates this hint open request
func (m *HintOpenRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateStatus(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

var hintOpenRequestTypeStatusPropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["open"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		hintOpenRequestTypeStatusPropEnum = append(hintOpenRequestTypeStatusPropEnum, v)
	}
}

const (

	// HintOpenRequestStatusOpen captures enum value "open"
	HintOpenRequestStatusOpen string = "open"
)

// prop value enum
func (m *HintOpenRequest) validateStatusEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, hintOpenRequestTypeStatusPropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *HintOpenRequest) validateStatus(formats strfmt.Registry) error {

	if err := validate.Required("status", "body", m.Status); err != nil {
		return err
	}

	// value enum
	if err := m.validateStatusEnum("status", "body", *m.Status); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this hint open request based on context it is used
func (m *HintOpenRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *HintOpenRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *HintOpenRequest) UnmarshalBinary(b []byte) error {
	var res HintOpenRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
