// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// TaskAnswerRequest task answer request
//
// swagger:model TaskAnswerRequest
type TaskAnswerRequest struct {

	// User submitted answer
	// Required: true
	// Min Length: 1
	Answer *string `json:"answer"`
}

// Validate validates this task answer request
func (m *TaskAnswerRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateAnswer(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *TaskAnswerRequest) validateAnswer(formats strfmt.Registry) error {

	if err := validate.Required("answer", "body", m.Answer); err != nil {
		return err
	}

	if err := validate.MinLength("answer", "body", *m.Answer, 1); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this task answer request based on context it is used
func (m *TaskAnswerRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *TaskAnswerRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *TaskAnswerRequest) UnmarshalBinary(b []byte) error {
	var res TaskAnswerRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
