// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// TaskAnswerResponse task answer response
//
// swagger:model TaskAnswerResponse
type TaskAnswerResponse struct {

	// Result of attempt
	// Required: true
	// Enum: [correct incorrect]
	Status *string `json:"status"`
}

// Validate validates this task answer response
func (m *TaskAnswerResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateStatus(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

var taskAnswerResponseTypeStatusPropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["correct","incorrect"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		taskAnswerResponseTypeStatusPropEnum = append(taskAnswerResponseTypeStatusPropEnum, v)
	}
}

const (

	// TaskAnswerResponseStatusCorrect captures enum value "correct"
	TaskAnswerResponseStatusCorrect string = "correct"

	// TaskAnswerResponseStatusIncorrect captures enum value "incorrect"
	TaskAnswerResponseStatusIncorrect string = "incorrect"
)

// prop value enum
func (m *TaskAnswerResponse) validateStatusEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, taskAnswerResponseTypeStatusPropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *TaskAnswerResponse) validateStatus(formats strfmt.Registry) error {

	if err := validate.Required("status", "body", m.Status); err != nil {
		return err
	}

	// value enum
	if err := m.validateStatusEnum("status", "body", *m.Status); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this task answer response based on context it is used
func (m *TaskAnswerResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *TaskAnswerResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *TaskAnswerResponse) UnmarshalBinary(b []byte) error {
	var res TaskAnswerResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
