// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// TeamTaskOverview team task overview
//
// swagger:model TeamTaskOverview
type TeamTaskOverview struct {

	// Task name
	// Required: true
	Name *string `json:"name"`

	// Task status for team
	// Required: true
	// Enum: [pending correct incorrect]
	Status *string `json:"status"`
}

// Validate validates this team task overview
func (m *TeamTaskOverview) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateName(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateStatus(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *TeamTaskOverview) validateName(formats strfmt.Registry) error {

	if err := validate.Required("name", "body", m.Name); err != nil {
		return err
	}

	return nil
}

var teamTaskOverviewTypeStatusPropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["pending","correct","incorrect"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		teamTaskOverviewTypeStatusPropEnum = append(teamTaskOverviewTypeStatusPropEnum, v)
	}
}

const (

	// TeamTaskOverviewStatusPending captures enum value "pending"
	TeamTaskOverviewStatusPending string = "pending"

	// TeamTaskOverviewStatusCorrect captures enum value "correct"
	TeamTaskOverviewStatusCorrect string = "correct"

	// TeamTaskOverviewStatusIncorrect captures enum value "incorrect"
	TeamTaskOverviewStatusIncorrect string = "incorrect"
)

// prop value enum
func (m *TeamTaskOverview) validateStatusEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, teamTaskOverviewTypeStatusPropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *TeamTaskOverview) validateStatus(formats strfmt.Registry) error {

	if err := validate.Required("status", "body", m.Status); err != nil {
		return err
	}

	// value enum
	if err := m.validateStatusEnum("status", "body", *m.Status); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this team task overview based on context it is used
func (m *TeamTaskOverview) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *TeamTaskOverview) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *TeamTaskOverview) UnmarshalBinary(b []byte) error {
	var res TeamTaskOverview
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
