// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// TeamTask team task
//
// swagger:model TeamTask
type TeamTask struct {

	// Task name
	// Required: true
	Name *string `json:"name"`

	// Task status for team
	// Required: true
	// Enum: [pending solved]
	Status *string `json:"status"`
}

// Validate validates this team task
func (m *TeamTask) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateName(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateStatus(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *TeamTask) validateName(formats strfmt.Registry) error {

	if err := validate.Required("name", "body", m.Name); err != nil {
		return err
	}

	return nil
}

var teamTaskTypeStatusPropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["pending","solved"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		teamTaskTypeStatusPropEnum = append(teamTaskTypeStatusPropEnum, v)
	}
}

const (

	// TeamTaskStatusPending captures enum value "pending"
	TeamTaskStatusPending string = "pending"

	// TeamTaskStatusSolved captures enum value "solved"
	TeamTaskStatusSolved string = "solved"
)

// prop value enum
func (m *TeamTask) validateStatusEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, teamTaskTypeStatusPropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *TeamTask) validateStatus(formats strfmt.Registry) error {

	if err := validate.Required("status", "body", m.Status); err != nil {
		return err
	}

	// value enum
	if err := m.validateStatusEnum("status", "body", *m.Status); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this team task based on context it is used
func (m *TeamTask) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *TeamTask) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *TeamTask) UnmarshalBinary(b []byte) error {
	var res TeamTask
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
