// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// Tournament tournament
//
// swagger:model Tournament
type Tournament struct {

	// attempts
	// Required: true
	Attempts []*Attempt `json:"attempts"`

	// Geographic coordinates
	// Required: true
	Coords *string `json:"coords"`

	// Tournament description
	// Required: true
	// Max Length: 300
	Description *string `json:"description"`

	// hints
	// Required: true
	Hints []*Hint `json:"hints"`

	// Tournament identifier
	// Required: true
	ID *int64 `json:"id"`

	// Tournament name
	// Required: true
	Name *string `json:"name"`

	// Current tournament status
	// Required: true
	// Enum: [in_progress done]
	Status *string `json:"status"`
}

// Validate validates this tournament
func (m *Tournament) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateAttempts(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateCoords(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateDescription(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateHints(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateName(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateStatus(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Tournament) validateAttempts(formats strfmt.Registry) error {

	if err := validate.Required("attempts", "body", m.Attempts); err != nil {
		return err
	}

	for i := 0; i < len(m.Attempts); i++ {
		if swag.IsZero(m.Attempts[i]) { // not required
			continue
		}

		if m.Attempts[i] != nil {
			if err := m.Attempts[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("attempts" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("attempts" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *Tournament) validateCoords(formats strfmt.Registry) error {

	if err := validate.Required("coords", "body", m.Coords); err != nil {
		return err
	}

	return nil
}

func (m *Tournament) validateDescription(formats strfmt.Registry) error {

	if err := validate.Required("description", "body", m.Description); err != nil {
		return err
	}

	if err := validate.MaxLength("description", "body", *m.Description, 300); err != nil {
		return err
	}

	return nil
}

func (m *Tournament) validateHints(formats strfmt.Registry) error {

	if err := validate.Required("hints", "body", m.Hints); err != nil {
		return err
	}

	for i := 0; i < len(m.Hints); i++ {
		if swag.IsZero(m.Hints[i]) { // not required
			continue
		}

		if m.Hints[i] != nil {
			if err := m.Hints[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("hints" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("hints" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *Tournament) validateID(formats strfmt.Registry) error {

	if err := validate.Required("id", "body", m.ID); err != nil {
		return err
	}

	return nil
}

func (m *Tournament) validateName(formats strfmt.Registry) error {

	if err := validate.Required("name", "body", m.Name); err != nil {
		return err
	}

	return nil
}

var tournamentTypeStatusPropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["in_progress","done"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		tournamentTypeStatusPropEnum = append(tournamentTypeStatusPropEnum, v)
	}
}

const (

	// TournamentStatusInProgress captures enum value "in_progress"
	TournamentStatusInProgress string = "in_progress"

	// TournamentStatusDone captures enum value "done"
	TournamentStatusDone string = "done"
)

// prop value enum
func (m *Tournament) validateStatusEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, tournamentTypeStatusPropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *Tournament) validateStatus(formats strfmt.Registry) error {

	if err := validate.Required("status", "body", m.Status); err != nil {
		return err
	}

	// value enum
	if err := m.validateStatusEnum("status", "body", *m.Status); err != nil {
		return err
	}

	return nil
}

// ContextValidate validate this tournament based on the context it is used
func (m *Tournament) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateAttempts(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateHints(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Tournament) contextValidateAttempts(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.Attempts); i++ {

		if m.Attempts[i] != nil {

			if swag.IsZero(m.Attempts[i]) { // not required
				return nil
			}

			if err := m.Attempts[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("attempts" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("attempts" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *Tournament) contextValidateHints(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.Hints); i++ {

		if m.Hints[i] != nil {

			if swag.IsZero(m.Hints[i]) { // not required
				return nil
			}

			if err := m.Hints[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("hints" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("hints" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *Tournament) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Tournament) UnmarshalBinary(b []byte) error {
	var res Tournament
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
