// Code generated by go-swagger; DO NOT EDIT.

package hints

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"kafka-playground/internal/api/models"
)

// GetTournamentsTournamentIDTasksTaskIDHintsHintIDOKCode is the HTTP code returned for type GetTournamentsTournamentIDTasksTaskIDHintsHintIDOK
const GetTournamentsTournamentIDTasksTaskIDHintsHintIDOKCode int = 200

/*
GetTournamentsTournamentIDTasksTaskIDHintsHintIDOK Hint details

swagger:response getTournamentsTournamentIdTasksTaskIdHintsHintIdOK
*/
type GetTournamentsTournamentIDTasksTaskIDHintsHintIDOK struct {

	/*
	  In: Body
	*/
	Payload *models.Hint `json:"body,omitempty"`
}

// NewGetTournamentsTournamentIDTasksTaskIDHintsHintIDOK creates GetTournamentsTournamentIDTasksTaskIDHintsHintIDOK with default headers values
func NewGetTournamentsTournamentIDTasksTaskIDHintsHintIDOK() *GetTournamentsTournamentIDTasksTaskIDHintsHintIDOK {

	return &GetTournamentsTournamentIDTasksTaskIDHintsHintIDOK{}
}

// WithPayload adds the payload to the get tournaments tournament Id tasks task Id hints hint Id o k response
func (o *GetTournamentsTournamentIDTasksTaskIDHintsHintIDOK) WithPayload(payload *models.Hint) *GetTournamentsTournamentIDTasksTaskIDHintsHintIDOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get tournaments tournament Id tasks task Id hints hint Id o k response
func (o *GetTournamentsTournamentIDTasksTaskIDHintsHintIDOK) SetPayload(payload *models.Hint) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetTournamentsTournamentIDTasksTaskIDHintsHintIDOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetTournamentsTournamentIDTasksTaskIDHintsHintIDUnauthorizedCode is the HTTP code returned for type GetTournamentsTournamentIDTasksTaskIDHintsHintIDUnauthorized
const GetTournamentsTournamentIDTasksTaskIDHintsHintIDUnauthorizedCode int = 401

/*
GetTournamentsTournamentIDTasksTaskIDHintsHintIDUnauthorized Unauthorized

swagger:response getTournamentsTournamentIdTasksTaskIdHintsHintIdUnauthorized
*/
type GetTournamentsTournamentIDTasksTaskIDHintsHintIDUnauthorized struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetTournamentsTournamentIDTasksTaskIDHintsHintIDUnauthorized creates GetTournamentsTournamentIDTasksTaskIDHintsHintIDUnauthorized with default headers values
func NewGetTournamentsTournamentIDTasksTaskIDHintsHintIDUnauthorized() *GetTournamentsTournamentIDTasksTaskIDHintsHintIDUnauthorized {

	return &GetTournamentsTournamentIDTasksTaskIDHintsHintIDUnauthorized{}
}

// WithPayload adds the payload to the get tournaments tournament Id tasks task Id hints hint Id unauthorized response
func (o *GetTournamentsTournamentIDTasksTaskIDHintsHintIDUnauthorized) WithPayload(payload *models.Error) *GetTournamentsTournamentIDTasksTaskIDHintsHintIDUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get tournaments tournament Id tasks task Id hints hint Id unauthorized response
func (o *GetTournamentsTournamentIDTasksTaskIDHintsHintIDUnauthorized) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetTournamentsTournamentIDTasksTaskIDHintsHintIDUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetTournamentsTournamentIDTasksTaskIDHintsHintIDForbiddenCode is the HTTP code returned for type GetTournamentsTournamentIDTasksTaskIDHintsHintIDForbidden
const GetTournamentsTournamentIDTasksTaskIDHintsHintIDForbiddenCode int = 403

/*
GetTournamentsTournamentIDTasksTaskIDHintsHintIDForbidden Forbidden

swagger:response getTournamentsTournamentIdTasksTaskIdHintsHintIdForbidden
*/
type GetTournamentsTournamentIDTasksTaskIDHintsHintIDForbidden struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetTournamentsTournamentIDTasksTaskIDHintsHintIDForbidden creates GetTournamentsTournamentIDTasksTaskIDHintsHintIDForbidden with default headers values
func NewGetTournamentsTournamentIDTasksTaskIDHintsHintIDForbidden() *GetTournamentsTournamentIDTasksTaskIDHintsHintIDForbidden {

	return &GetTournamentsTournamentIDTasksTaskIDHintsHintIDForbidden{}
}

// WithPayload adds the payload to the get tournaments tournament Id tasks task Id hints hint Id forbidden response
func (o *GetTournamentsTournamentIDTasksTaskIDHintsHintIDForbidden) WithPayload(payload *models.Error) *GetTournamentsTournamentIDTasksTaskIDHintsHintIDForbidden {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get tournaments tournament Id tasks task Id hints hint Id forbidden response
func (o *GetTournamentsTournamentIDTasksTaskIDHintsHintIDForbidden) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetTournamentsTournamentIDTasksTaskIDHintsHintIDForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(403)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetTournamentsTournamentIDTasksTaskIDHintsHintIDNotFoundCode is the HTTP code returned for type GetTournamentsTournamentIDTasksTaskIDHintsHintIDNotFound
const GetTournamentsTournamentIDTasksTaskIDHintsHintIDNotFoundCode int = 404

/*
GetTournamentsTournamentIDTasksTaskIDHintsHintIDNotFound Resource not found

swagger:response getTournamentsTournamentIdTasksTaskIdHintsHintIdNotFound
*/
type GetTournamentsTournamentIDTasksTaskIDHintsHintIDNotFound struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetTournamentsTournamentIDTasksTaskIDHintsHintIDNotFound creates GetTournamentsTournamentIDTasksTaskIDHintsHintIDNotFound with default headers values
func NewGetTournamentsTournamentIDTasksTaskIDHintsHintIDNotFound() *GetTournamentsTournamentIDTasksTaskIDHintsHintIDNotFound {

	return &GetTournamentsTournamentIDTasksTaskIDHintsHintIDNotFound{}
}

// WithPayload adds the payload to the get tournaments tournament Id tasks task Id hints hint Id not found response
func (o *GetTournamentsTournamentIDTasksTaskIDHintsHintIDNotFound) WithPayload(payload *models.Error) *GetTournamentsTournamentIDTasksTaskIDHintsHintIDNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get tournaments tournament Id tasks task Id hints hint Id not found response
func (o *GetTournamentsTournamentIDTasksTaskIDHintsHintIDNotFound) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetTournamentsTournamentIDTasksTaskIDHintsHintIDNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
