// Code generated by go-swagger; DO NOT EDIT.

package hints

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetTournamentsTournamentIDTasksTaskIDHintsHintIDHandlerFunc turns a function with the right signature into a get tournaments tournament ID tasks task ID hints hint ID handler
type GetTournamentsTournamentIDTasksTaskIDHintsHintIDHandlerFunc func(GetTournamentsTournamentIDTasksTaskIDHintsHintIDParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetTournamentsTournamentIDTasksTaskIDHintsHintIDHandlerFunc) Handle(params GetTournamentsTournamentIDTasksTaskIDHintsHintIDParams) middleware.Responder {
	return fn(params)
}

// GetTournamentsTournamentIDTasksTaskIDHintsHintIDHandler interface for that can handle valid get tournaments tournament ID tasks task ID hints hint ID params
type GetTournamentsTournamentIDTasksTaskIDHintsHintIDHandler interface {
	Handle(GetTournamentsTournamentIDTasksTaskIDHintsHintIDParams) middleware.Responder
}

// NewGetTournamentsTournamentIDTasksTaskIDHintsHintID creates a new http.Handler for the get tournaments tournament ID tasks task ID hints hint ID operation
func NewGetTournamentsTournamentIDTasksTaskIDHintsHintID(ctx *middleware.Context, handler GetTournamentsTournamentIDTasksTaskIDHintsHintIDHandler) *GetTournamentsTournamentIDTasksTaskIDHintsHintID {
	return &GetTournamentsTournamentIDTasksTaskIDHintsHintID{Context: ctx, Handler: handler}
}

/*
	GetTournamentsTournamentIDTasksTaskIDHintsHintID swagger:route GET /tournaments/{tournamentId}/tasks/{taskId}/hints/{hintId} hints getTournamentsTournamentIdTasksTaskIdHintsHintId

Get hint details
*/
type GetTournamentsTournamentIDTasksTaskIDHintsHintID struct {
	Context *middleware.Context
	Handler GetTournamentsTournamentIDTasksTaskIDHintsHintIDHandler
}

func (o *GetTournamentsTournamentIDTasksTaskIDHintsHintID) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetTournamentsTournamentIDTasksTaskIDHintsHintIDParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
