// Code generated by go-swagger; DO NOT EDIT.

package hints

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"errors"
	"net/url"
	golangswaggerpaths "path"
	"strings"

	"github.com/go-openapi/swag"
)

// PatchTournamentsTournamentIDTasksTaskIDHintsHintIDURL generates an URL for the patch tournaments tournament ID tasks task ID hints hint ID operation
type PatchTournamentsTournamentIDTasksTaskIDHintsHintIDURL struct {
	HintID       int64
	TaskID       int64
	TournamentID int64

	_basePath string
	// avoid unkeyed usage
	_ struct{}
}

// WithBasePath sets the base path for this url builder, only required when it's different from the
// base path specified in the swagger spec.
// When the value of the base path is an empty string
func (o *PatchTournamentsTournamentIDTasksTaskIDHintsHintIDURL) WithBasePath(bp string) *PatchTournamentsTournamentIDTasksTaskIDHintsHintIDURL {
	o.SetBasePath(bp)
	return o
}

// SetBasePath sets the base path for this url builder, only required when it's different from the
// base path specified in the swagger spec.
// When the value of the base path is an empty string
func (o *PatchTournamentsTournamentIDTasksTaskIDHintsHintIDURL) SetBasePath(bp string) {
	o._basePath = bp
}

// Build a url path and query string
func (o *PatchTournamentsTournamentIDTasksTaskIDHintsHintIDURL) Build() (*url.URL, error) {
	var _result url.URL

	var _path = "/tournaments/{tournamentId}/tasks/{taskId}/hints/{hintId}"

	hintID := swag.FormatInt64(o.HintID)
	if hintID != "" {
		_path = strings.Replace(_path, "{hintId}", hintID, -1)
	} else {
		return nil, errors.New("hintId is required on PatchTournamentsTournamentIDTasksTaskIDHintsHintIDURL")
	}

	taskID := swag.FormatInt64(o.TaskID)
	if taskID != "" {
		_path = strings.Replace(_path, "{taskId}", taskID, -1)
	} else {
		return nil, errors.New("taskId is required on PatchTournamentsTournamentIDTasksTaskIDHintsHintIDURL")
	}

	tournamentID := swag.FormatInt64(o.TournamentID)
	if tournamentID != "" {
		_path = strings.Replace(_path, "{tournamentId}", tournamentID, -1)
	} else {
		return nil, errors.New("tournamentId is required on PatchTournamentsTournamentIDTasksTaskIDHintsHintIDURL")
	}

	_basePath := o._basePath
	if _basePath == "" {
		_basePath = "/"
	}
	_result.Path = golangswaggerpaths.Join(_basePath, _path)

	return &_result, nil
}

// Must is a helper function to panic when the url builder returns an error
func (o *PatchTournamentsTournamentIDTasksTaskIDHintsHintIDURL) Must(u *url.URL, err error) *url.URL {
	if err != nil {
		panic(err)
	}
	if u == nil {
		panic("url can't be nil")
	}
	return u
}

// String returns the string representation of the path with query string
func (o *PatchTournamentsTournamentIDTasksTaskIDHintsHintIDURL) String() string {
	return o.Must(o.Build()).String()
}

// BuildFull builds a full url with scheme, host, path and query string
func (o *PatchTournamentsTournamentIDTasksTaskIDHintsHintIDURL) BuildFull(scheme, host string) (*url.URL, error) {
	if scheme == "" {
		return nil, errors.New("scheme is required for a full url on PatchTournamentsTournamentIDTasksTaskIDHintsHintIDURL")
	}
	if host == "" {
		return nil, errors.New("host is required for a full url on PatchTournamentsTournamentIDTasksTaskIDHintsHintIDURL")
	}

	base, err := o.Build()
	if err != nil {
		return nil, err
	}

	base.Scheme = scheme
	base.Host = host
	return base, nil
}

// StringFull returns the string representation of a complete url
func (o *PatchTournamentsTournamentIDTasksTaskIDHintsHintIDURL) StringFull(scheme, host string) string {
	return o.Must(o.BuildFull(scheme, host)).String()
}
