// Code generated by go-swagger; DO NOT EDIT.

package hints

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"io"
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"

	"kafka-playground/internal/api/models"
)

// NewPatchTournamentsTournamentIDTasksTaskIDHintsHintIDParams creates a new PatchTournamentsTournamentIDTasksTaskIDHintsHintIDParams object
//
// There are no default values defined in the spec.
func NewPatchTournamentsTournamentIDTasksTaskIDHintsHintIDParams() PatchTournamentsTournamentIDTasksTaskIDHintsHintIDParams {

	return PatchTournamentsTournamentIDTasksTaskIDHintsHintIDParams{}
}

// PatchTournamentsTournamentIDTasksTaskIDHintsHintIDParams contains all the bound params for the patch tournaments tournament ID tasks task ID hints hint ID operation
// typically these are obtained from a http.Request
//
// swagger:parameters PatchTournamentsTournamentIDTasksTaskIDHintsHintID
type PatchTournamentsTournamentIDTasksTaskIDHintsHintIDParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*
	  Required: true
	  In: path
	*/
	HintID int64
	/*
	  Required: true
	  In: body
	*/
	Status *models.HintOpenRequest
	/*
	  Required: true
	  In: path
	*/
	TaskID int64
	/*
	  Required: true
	  In: path
	*/
	TournamentID int64
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewPatchTournamentsTournamentIDTasksTaskIDHintsHintIDParams() beforehand.
func (o *PatchTournamentsTournamentIDTasksTaskIDHintsHintIDParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	rHintID, rhkHintID, _ := route.Params.GetOK("hintId")
	if err := o.bindHintID(rHintID, rhkHintID, route.Formats); err != nil {
		res = append(res, err)
	}

	if runtime.HasBody(r) {
		defer r.Body.Close()
		var body models.HintOpenRequest
		if err := route.Consumer.Consume(r.Body, &body); err != nil {
			if err == io.EOF {
				res = append(res, errors.Required("status", "body", ""))
			} else {
				res = append(res, errors.NewParseError("status", "body", "", err))
			}
		} else {
			// validate body object
			if err := body.Validate(route.Formats); err != nil {
				res = append(res, err)
			}

			ctx := validate.WithOperationRequest(r.Context())
			if err := body.ContextValidate(ctx, route.Formats); err != nil {
				res = append(res, err)
			}

			if len(res) == 0 {
				o.Status = &body
			}
		}
	} else {
		res = append(res, errors.Required("status", "body", ""))
	}

	rTaskID, rhkTaskID, _ := route.Params.GetOK("taskId")
	if err := o.bindTaskID(rTaskID, rhkTaskID, route.Formats); err != nil {
		res = append(res, err)
	}

	rTournamentID, rhkTournamentID, _ := route.Params.GetOK("tournamentId")
	if err := o.bindTournamentID(rTournamentID, rhkTournamentID, route.Formats); err != nil {
		res = append(res, err)
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindHintID binds and validates parameter HintID from path.
func (o *PatchTournamentsTournamentIDTasksTaskIDHintsHintIDParams) bindHintID(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route

	value, err := swag.ConvertInt64(raw)
	if err != nil {
		return errors.InvalidType("hintId", "path", "int64", raw)
	}
	o.HintID = value

	return nil
}

// bindTaskID binds and validates parameter TaskID from path.
func (o *PatchTournamentsTournamentIDTasksTaskIDHintsHintIDParams) bindTaskID(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route

	value, err := swag.ConvertInt64(raw)
	if err != nil {
		return errors.InvalidType("taskId", "path", "int64", raw)
	}
	o.TaskID = value

	return nil
}

// bindTournamentID binds and validates parameter TournamentID from path.
func (o *PatchTournamentsTournamentIDTasksTaskIDHintsHintIDParams) bindTournamentID(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route

	value, err := swag.ConvertInt64(raw)
	if err != nil {
		return errors.InvalidType("tournamentId", "path", "int64", raw)
	}
	o.TournamentID = value

	return nil
}
