// Code generated by go-swagger; DO NOT EDIT.

package tournaments

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetTournamentsTournamentIDHandlerFunc turns a function with the right signature into a get tournaments tournament ID handler
type GetTournamentsTournamentIDHandlerFunc func(GetTournamentsTournamentIDParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetTournamentsTournamentIDHandlerFunc) Handle(params GetTournamentsTournamentIDParams) middleware.Responder {
	return fn(params)
}

// GetTournamentsTournamentIDHandler interface for that can handle valid get tournaments tournament ID params
type GetTournamentsTournamentIDHandler interface {
	Handle(GetTournamentsTournamentIDParams) middleware.Responder
}

// NewGetTournamentsTournamentID creates a new http.Handler for the get tournaments tournament ID operation
func NewGetTournamentsTournamentID(ctx *middleware.Context, handler GetTournamentsTournamentIDHandler) *GetTournamentsTournamentID {
	return &GetTournamentsTournamentID{Context: ctx, Handler: handler}
}

/*
	GetTournamentsTournamentID swagger:route GET /tournaments/{tournamentId}/ tournaments getTournamentsTournamentId

Get tournament details
*/
type GetTournamentsTournamentID struct {
	Context *middleware.Context
	Handler GetTournamentsTournamentIDHandler
}

func (o *GetTournamentsTournamentID) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetTournamentsTournamentIDParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
