// Code generated by go-swagger; DO NOT EDIT.

package tournaments

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"kafka-playground/internal/api/models"
)

// GetTournamentsOKCode is the HTTP code returned for type GetTournamentsOK
const GetTournamentsOKCode int = 200

/*
GetTournamentsOK Tournament leaderboard

swagger:response getTournamentsOK
*/
type GetTournamentsOK struct {

	/*
	  In: Body
	*/
	Payload *models.TournamentOverview `json:"body,omitempty"`
}

// NewGetTournamentsOK creates GetTournamentsOK with default headers values
func NewGetTournamentsOK() *GetTournamentsOK {

	return &GetTournamentsOK{}
}

// WithPayload adds the payload to the get tournaments o k response
func (o *GetTournamentsOK) WithPayload(payload *models.TournamentOverview) *GetTournamentsOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get tournaments o k response
func (o *GetTournamentsOK) SetPayload(payload *models.TournamentOverview) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetTournamentsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetTournamentsUnauthorizedCode is the HTTP code returned for type GetTournamentsUnauthorized
const GetTournamentsUnauthorizedCode int = 401

/*
GetTournamentsUnauthorized Unauthorized

swagger:response getTournamentsUnauthorized
*/
type GetTournamentsUnauthorized struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetTournamentsUnauthorized creates GetTournamentsUnauthorized with default headers values
func NewGetTournamentsUnauthorized() *GetTournamentsUnauthorized {

	return &GetTournamentsUnauthorized{}
}

// WithPayload adds the payload to the get tournaments unauthorized response
func (o *GetTournamentsUnauthorized) WithPayload(payload *models.Error) *GetTournamentsUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get tournaments unauthorized response
func (o *GetTournamentsUnauthorized) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetTournamentsUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetTournamentsForbiddenCode is the HTTP code returned for type GetTournamentsForbidden
const GetTournamentsForbiddenCode int = 403

/*
GetTournamentsForbidden Forbidden

swagger:response getTournamentsForbidden
*/
type GetTournamentsForbidden struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetTournamentsForbidden creates GetTournamentsForbidden with default headers values
func NewGetTournamentsForbidden() *GetTournamentsForbidden {

	return &GetTournamentsForbidden{}
}

// WithPayload adds the payload to the get tournaments forbidden response
func (o *GetTournamentsForbidden) WithPayload(payload *models.Error) *GetTournamentsForbidden {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get tournaments forbidden response
func (o *GetTournamentsForbidden) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetTournamentsForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(403)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
