// Code generated by go-swagger; DO NOT EDIT.

package tournaments

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"
)

// NewGetTournamentsParams creates a new GetTournamentsParams object
//
// There are no default values defined in the spec.
func NewGetTournamentsParams() GetTournamentsParams {

	return GetTournamentsParams{}
}

// GetTournamentsParams contains all the bound params for the get tournaments operation
// typically these are obtained from a http.Request
//
// swagger:parameters GetTournaments
type GetTournamentsParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewGetTournamentsParams() beforehand.
func (o *GetTournamentsParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
