swagger: "2.0"
info:
  title: Tournament API
  version: "1.0.0"
  description: API for tournament management and participation
host: api.example.com
basePath: /
schemes:
  - https
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
  /login:
    post:
      tags: [auth]
      summary: Authenticate user
      parameters:
        - in: body
          name: credentials
          required: true
          schema:
            $ref: '#/definitions/LoginRequest'
      responses:
        '200':
          description: Successful authentication
          schema:
            $ref: '#/definitions/LoginResponse'
        '400':
          $ref: '#/responses/BadRequest'
  /tournaments/{tournamentId}/:
    get:
      tags: [tournaments]
      summary: Get tournament details
      parameters:
        - name: tournamentId
          in: path
          required: true
          type: integer
      responses:
        '200':
          description: Tournament details
          schema:
            $ref: '#/definitions/Tournament'
        '401':
          $ref: '#/responses/Unauthorized'
        '403':
          $ref: '#/responses/Forbidden'
  /tournaments/{tournamentId}/tasks/{taskId}:
    get:
      tags: [tasks]
      summary: Get task details
      parameters:
        - name: tournamentId
          in: path
          required: true
          type: integer
        - name: taskId
          in: path
          required: true
          type: integer
      responses:
        '200':
          description: Team task details
          schema:
            $ref: '#/definitions/TeamTask'
        '401':
          $ref: '#/responses/Unauthorized'
        '403':
          $ref: '#/responses/Forbidden'
        '404':
          $ref: '#/responses/NotFound'
    patch:
      tags: [tasks]
      summary: Submit answer for task
      parameters:
        - name: tournamentId
          in: path
          required: true
          type: integer
        - name: taskId
          in: path
          required: true
          type: integer
        - in: body
          name: answer
          required: true
          schema:
            $ref: '#/definitions/TaskAnswerRequest'
      responses:
        '200':
          description: Answer processed
          schema:
            $ref: '#/definitions/TaskAnswerResponse'
        '400':
          $ref: '#/responses/BadRequest'
        '409':
          $ref: '#/responses/TooManyAttempts'
        '401':
          $ref: '#/responses/Unauthorized'
        '403':
          $ref: '#/responses/Forbidden'
        '404':
          $ref: '#/responses/NotFound'
  /tournaments/{tournamentId}/tasks/{taskId}/hints/{hintId}:
    get:
      tags: [hints]
      summary: Get hint details
      parameters:
        - name: tournamentId
          in: path
          required: true
          type: integer
        - name: taskId
          in: path
          required: true
          type: integer
        - name: hintId
          in: path
          required: true
          type: integer
      responses:
        '200':
          description: Hint details
          schema:
            $ref: '#/definitions/Hint'
        '401':
          $ref: '#/responses/Unauthorized'
        '403':
          $ref: '#/responses/Forbidden'
        '404':
          $ref: '#/responses/NotFound'
    patch:
      tags: [hints]
      summary: Open hint for task
      parameters:
        - name: tournamentId
          in: path
          required: true
          type: integer
        - name: taskId
          in: path
          required: true
          type: integer
        - name: hintId
          in: path
          required: true
          type: integer
        - in: body
          name: status
          required: true
          schema:
            $ref: '#/definitions/HintOpenRequest'
      responses:
        '200':
          description: Hint opened
          schema:
            $ref: '#/definitions/Hint'
        '401':
          $ref: '#/responses/Unauthorized'
        '403':
          $ref: '#/responses/Forbidden'
        '404':
          $ref: '#/responses/NotFound'
  /tournaments:
    get:
      tags: [tournaments]
      summary: Get active tournament and leaderboard
      responses:
        '200':
          description: Tournament leaderboard
          schema:
            $ref: '#/definitions/TournamentOverview'
        '401':
          $ref: '#/responses/Unauthorized'
        '403':
          $ref: '#/responses/Forbidden'
definitions:
  LoginRequest:
    $ref: 'components/schemas/LoginRequest.yaml'
  LoginResponse:
    $ref: 'components/schemas/LoginResponse.yaml'
  Error:
    $ref: 'components/schemas/Error.yaml'
  Attempt:
    $ref: 'components/schemas/Attempt.yaml'
  Hint:
    $ref: 'components/schemas/Hint.yaml'
  Tournament:
    $ref: 'components/schemas/Tournament.yaml'
  TaskAnswerRequest:
    $ref: 'components/schemas/TaskAnswerRequest.yaml'
  TaskAnswerResponse:
    $ref: 'components/schemas/TaskAnswerResponse.yaml'
  HintOpenRequest:
    $ref: 'components/schemas/HintOpenRequest.yaml'
  TeamTask:
    $ref: 'components/schemas/TeamTask.yaml'
  TeamTaskOverview:
    $ref: 'components/schemas/TeamTaskOverview.yaml'
  TeamOverview:
    $ref: 'components/schemas/TeamOverview.yaml'
  Task:
    $ref: 'components/schemas/Task.yaml'
  TournamentOverview:
    $ref: 'components/schemas/TournamentOverview.yaml'
responses:
  BadRequest:
    description: Bad request
    schema:
      $ref: '#/definitions/Error'
  Unauthorized:
    description: Unauthorized
    schema:
      $ref: '#/definitions/Error'
  Forbidden:
    description: Forbidden
    schema:
      $ref: '#/definitions/Error'
  NotFound:
    description: Resource not found
    schema:
      $ref: '#/definitions/Error'
  TooManyAttempts:
    description: Maximum attempts exceeded
    schema:
      $ref: '#/definitions/Error'
tags:
  - name: auth
    description: Authentication and authorization
  - name: tournaments
    description: Tournament operations
  - name: tasks
    description: Task operations
  - name: hints
    description: Hint operations

