// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"net/http"
	"strings"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/loads"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/runtime/security"
	"github.com/go-openapi/spec"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"kafka-playground/internal/api/restapi/operations/auth"
	"kafka-playground/internal/api/restapi/operations/hints"
	"kafka-playground/internal/api/restapi/operations/tasks"
	"kafka-playground/internal/api/restapi/operations/tournaments"
)

// NewTournamentAPI creates a new Tournament instance
func NewTournamentAPI(spec *loads.Document) *TournamentAPI {
	return &TournamentAPI{
		handlers:            make(map[string]map[string]http.Handler),
		formats:             strfmt.Default,
		defaultConsumes:     "application/json",
		defaultProduces:     "application/json",
		customConsumers:     make(map[string]runtime.Consumer),
		customProducers:     make(map[string]runtime.Producer),
		PreServerShutdown:   func() {},
		ServerShutdown:      func() {},
		spec:                spec,
		useSwaggerUI:        false,
		ServeError:          errors.ServeError,
		BasicAuthenticator:  security.BasicAuth,
		APIKeyAuthenticator: security.APIKeyAuth,
		BearerAuthenticator: security.BearerAuth,

		JSONConsumer: runtime.JSONConsumer(),

		JSONProducer: runtime.JSONProducer(),

		TournamentsGetTournamentsHandler: tournaments.GetTournamentsHandlerFunc(func(params tournaments.GetTournamentsParams) middleware.Responder {
			return middleware.NotImplemented("operation tournaments.GetTournaments has not yet been implemented")
		}),
		TournamentsGetTournamentsTournamentIDHandler: tournaments.GetTournamentsTournamentIDHandlerFunc(func(params tournaments.GetTournamentsTournamentIDParams) middleware.Responder {
			return middleware.NotImplemented("operation tournaments.GetTournamentsTournamentID has not yet been implemented")
		}),
		TasksGetTournamentsTournamentIDTasksTaskIDHandler: tasks.GetTournamentsTournamentIDTasksTaskIDHandlerFunc(func(params tasks.GetTournamentsTournamentIDTasksTaskIDParams) middleware.Responder {
			return middleware.NotImplemented("operation tasks.GetTournamentsTournamentIDTasksTaskID has not yet been implemented")
		}),
		HintsGetTournamentsTournamentIDTasksTaskIDHintsHintIDHandler: hints.GetTournamentsTournamentIDTasksTaskIDHintsHintIDHandlerFunc(func(params hints.GetTournamentsTournamentIDTasksTaskIDHintsHintIDParams) middleware.Responder {
			return middleware.NotImplemented("operation hints.GetTournamentsTournamentIDTasksTaskIDHintsHintID has not yet been implemented")
		}),
		TasksPatchTournamentsTournamentIDTasksTaskIDHandler: tasks.PatchTournamentsTournamentIDTasksTaskIDHandlerFunc(func(params tasks.PatchTournamentsTournamentIDTasksTaskIDParams) middleware.Responder {
			return middleware.NotImplemented("operation tasks.PatchTournamentsTournamentIDTasksTaskID has not yet been implemented")
		}),
		HintsPatchTournamentsTournamentIDTasksTaskIDHintsHintIDHandler: hints.PatchTournamentsTournamentIDTasksTaskIDHintsHintIDHandlerFunc(func(params hints.PatchTournamentsTournamentIDTasksTaskIDHintsHintIDParams) middleware.Responder {
			return middleware.NotImplemented("operation hints.PatchTournamentsTournamentIDTasksTaskIDHintsHintID has not yet been implemented")
		}),
		AuthPostLoginHandler: auth.PostLoginHandlerFunc(func(params auth.PostLoginParams) middleware.Responder {
			return middleware.NotImplemented("operation auth.PostLogin has not yet been implemented")
		}),
	}
}

/*TournamentAPI API for tournament management and participation */
type TournamentAPI struct {
	spec            *loads.Document
	context         *middleware.Context
	handlers        map[string]map[string]http.Handler
	formats         strfmt.Registry
	customConsumers map[string]runtime.Consumer
	customProducers map[string]runtime.Producer
	defaultConsumes string
	defaultProduces string
	Middleware      func(middleware.Builder) http.Handler
	useSwaggerUI    bool

	// BasicAuthenticator generates a runtime.Authenticator from the supplied basic auth function.
	// It has a default implementation in the security package, however you can replace it for your particular usage.
	BasicAuthenticator func(security.UserPassAuthentication) runtime.Authenticator

	// APIKeyAuthenticator generates a runtime.Authenticator from the supplied token auth function.
	// It has a default implementation in the security package, however you can replace it for your particular usage.
	APIKeyAuthenticator func(string, string, security.TokenAuthentication) runtime.Authenticator

	// BearerAuthenticator generates a runtime.Authenticator from the supplied bearer token auth function.
	// It has a default implementation in the security package, however you can replace it for your particular usage.
	BearerAuthenticator func(string, security.ScopedTokenAuthentication) runtime.Authenticator

	// JSONConsumer registers a consumer for the following mime types:
	//   - application/json
	JSONConsumer runtime.Consumer

	// JSONProducer registers a producer for the following mime types:
	//   - application/json
	JSONProducer runtime.Producer

	// TournamentsGetTournamentsHandler sets the operation handler for the get tournaments operation
	TournamentsGetTournamentsHandler tournaments.GetTournamentsHandler
	// TournamentsGetTournamentsTournamentIDHandler sets the operation handler for the get tournaments tournament ID operation
	TournamentsGetTournamentsTournamentIDHandler tournaments.GetTournamentsTournamentIDHandler
	// TasksGetTournamentsTournamentIDTasksTaskIDHandler sets the operation handler for the get tournaments tournament ID tasks task ID operation
	TasksGetTournamentsTournamentIDTasksTaskIDHandler tasks.GetTournamentsTournamentIDTasksTaskIDHandler
	// HintsGetTournamentsTournamentIDTasksTaskIDHintsHintIDHandler sets the operation handler for the get tournaments tournament ID tasks task ID hints hint ID operation
	HintsGetTournamentsTournamentIDTasksTaskIDHintsHintIDHandler hints.GetTournamentsTournamentIDTasksTaskIDHintsHintIDHandler
	// TasksPatchTournamentsTournamentIDTasksTaskIDHandler sets the operation handler for the patch tournaments tournament ID tasks task ID operation
	TasksPatchTournamentsTournamentIDTasksTaskIDHandler tasks.PatchTournamentsTournamentIDTasksTaskIDHandler
	// HintsPatchTournamentsTournamentIDTasksTaskIDHintsHintIDHandler sets the operation handler for the patch tournaments tournament ID tasks task ID hints hint ID operation
	HintsPatchTournamentsTournamentIDTasksTaskIDHintsHintIDHandler hints.PatchTournamentsTournamentIDTasksTaskIDHintsHintIDHandler
	// AuthPostLoginHandler sets the operation handler for the post login operation
	AuthPostLoginHandler auth.PostLoginHandler

	// ServeError is called when an error is received, there is a default handler
	// but you can set your own with this
	ServeError func(http.ResponseWriter, *http.Request, error)

	// PreServerShutdown is called before the HTTP(S) server is shutdown
	// This allows for custom functions to get executed before the HTTP(S) server stops accepting traffic
	PreServerShutdown func()

	// ServerShutdown is called when the HTTP(S) server is shut down and done
	// handling all active connections and does not accept connections any more
	ServerShutdown func()

	// Custom command line argument groups with their descriptions
	CommandLineOptionsGroups []swag.CommandLineOptionsGroup

	// User defined logger function.
	Logger func(string, ...interface{})
}

// UseRedoc for documentation at /docs
func (o *TournamentAPI) UseRedoc() {
	o.useSwaggerUI = false
}

// UseSwaggerUI for documentation at /docs
func (o *TournamentAPI) UseSwaggerUI() {
	o.useSwaggerUI = true
}

// SetDefaultProduces sets the default produces media type
func (o *TournamentAPI) SetDefaultProduces(mediaType string) {
	o.defaultProduces = mediaType
}

// SetDefaultConsumes returns the default consumes media type
func (o *TournamentAPI) SetDefaultConsumes(mediaType string) {
	o.defaultConsumes = mediaType
}

// SetSpec sets a spec that will be served for the clients.
func (o *TournamentAPI) SetSpec(spec *loads.Document) {
	o.spec = spec
}

// DefaultProduces returns the default produces media type
func (o *TournamentAPI) DefaultProduces() string {
	return o.defaultProduces
}

// DefaultConsumes returns the default consumes media type
func (o *TournamentAPI) DefaultConsumes() string {
	return o.defaultConsumes
}

// Formats returns the registered string formats
func (o *TournamentAPI) Formats() strfmt.Registry {
	return o.formats
}

// RegisterFormat registers a custom format validator
func (o *TournamentAPI) RegisterFormat(name string, format strfmt.Format, validator strfmt.Validator) {
	o.formats.Add(name, format, validator)
}

// Validate validates the registrations in the TournamentAPI
func (o *TournamentAPI) Validate() error {
	var unregistered []string

	if o.JSONConsumer == nil {
		unregistered = append(unregistered, "JSONConsumer")
	}

	if o.JSONProducer == nil {
		unregistered = append(unregistered, "JSONProducer")
	}

	if o.TournamentsGetTournamentsHandler == nil {
		unregistered = append(unregistered, "tournaments.GetTournamentsHandler")
	}
	if o.TournamentsGetTournamentsTournamentIDHandler == nil {
		unregistered = append(unregistered, "tournaments.GetTournamentsTournamentIDHandler")
	}
	if o.TasksGetTournamentsTournamentIDTasksTaskIDHandler == nil {
		unregistered = append(unregistered, "tasks.GetTournamentsTournamentIDTasksTaskIDHandler")
	}
	if o.HintsGetTournamentsTournamentIDTasksTaskIDHintsHintIDHandler == nil {
		unregistered = append(unregistered, "hints.GetTournamentsTournamentIDTasksTaskIDHintsHintIDHandler")
	}
	if o.TasksPatchTournamentsTournamentIDTasksTaskIDHandler == nil {
		unregistered = append(unregistered, "tasks.PatchTournamentsTournamentIDTasksTaskIDHandler")
	}
	if o.HintsPatchTournamentsTournamentIDTasksTaskIDHintsHintIDHandler == nil {
		unregistered = append(unregistered, "hints.PatchTournamentsTournamentIDTasksTaskIDHintsHintIDHandler")
	}
	if o.AuthPostLoginHandler == nil {
		unregistered = append(unregistered, "auth.PostLoginHandler")
	}

	if len(unregistered) > 0 {
		return fmt.Errorf("missing registration: %s", strings.Join(unregistered, ", "))
	}

	return nil
}

// ServeErrorFor gets a error handler for a given operation id
func (o *TournamentAPI) ServeErrorFor(operationID string) func(http.ResponseWriter, *http.Request, error) {
	return o.ServeError
}

// AuthenticatorsFor gets the authenticators for the specified security schemes
func (o *TournamentAPI) AuthenticatorsFor(schemes map[string]spec.SecurityScheme) map[string]runtime.Authenticator {
	return nil
}

// Authorizer returns the registered authorizer
func (o *TournamentAPI) Authorizer() runtime.Authorizer {
	return nil
}

// ConsumersFor gets the consumers for the specified media types.
// MIME type parameters are ignored here.
func (o *TournamentAPI) ConsumersFor(mediaTypes []string) map[string]runtime.Consumer {
	result := make(map[string]runtime.Consumer, len(mediaTypes))
	for _, mt := range mediaTypes {
		switch mt {
		case "application/json":
			result["application/json"] = o.JSONConsumer
		}

		if c, ok := o.customConsumers[mt]; ok {
			result[mt] = c
		}
	}
	return result
}

// ProducersFor gets the producers for the specified media types.
// MIME type parameters are ignored here.
func (o *TournamentAPI) ProducersFor(mediaTypes []string) map[string]runtime.Producer {
	result := make(map[string]runtime.Producer, len(mediaTypes))
	for _, mt := range mediaTypes {
		switch mt {
		case "application/json":
			result["application/json"] = o.JSONProducer
		}

		if p, ok := o.customProducers[mt]; ok {
			result[mt] = p
		}
	}
	return result
}

// HandlerFor gets a http.Handler for the provided operation method and path
func (o *TournamentAPI) HandlerFor(method, path string) (http.Handler, bool) {
	if o.handlers == nil {
		return nil, false
	}
	um := strings.ToUpper(method)
	if _, ok := o.handlers[um]; !ok {
		return nil, false
	}
	if path == "/" {
		path = ""
	}
	h, ok := o.handlers[um][path]
	return h, ok
}

// Context returns the middleware context for the tournament API
func (o *TournamentAPI) Context() *middleware.Context {
	if o.context == nil {
		o.context = middleware.NewRoutableContext(o.spec, o, nil)
	}

	return o.context
}

func (o *TournamentAPI) initHandlerCache() {
	o.Context() // don't care about the result, just that the initialization happened
	if o.handlers == nil {
		o.handlers = make(map[string]map[string]http.Handler)
	}

	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/tournaments"] = tournaments.NewGetTournaments(o.context, o.TournamentsGetTournamentsHandler)
	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/tournaments/{tournamentId}"] = tournaments.NewGetTournamentsTournamentID(o.context, o.TournamentsGetTournamentsTournamentIDHandler)
	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/tournaments/{tournamentId}/tasks/{taskId}"] = tasks.NewGetTournamentsTournamentIDTasksTaskID(o.context, o.TasksGetTournamentsTournamentIDTasksTaskIDHandler)
	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/tournaments/{tournamentId}/tasks/{taskId}/hints/{hintId}"] = hints.NewGetTournamentsTournamentIDTasksTaskIDHintsHintID(o.context, o.HintsGetTournamentsTournamentIDTasksTaskIDHintsHintIDHandler)
	if o.handlers["PATCH"] == nil {
		o.handlers["PATCH"] = make(map[string]http.Handler)
	}
	o.handlers["PATCH"]["/tournaments/{tournamentId}/tasks/{taskId}"] = tasks.NewPatchTournamentsTournamentIDTasksTaskID(o.context, o.TasksPatchTournamentsTournamentIDTasksTaskIDHandler)
	if o.handlers["PATCH"] == nil {
		o.handlers["PATCH"] = make(map[string]http.Handler)
	}
	o.handlers["PATCH"]["/tournaments/{tournamentId}/tasks/{taskId}/hints/{hintId}"] = hints.NewPatchTournamentsTournamentIDTasksTaskIDHintsHintID(o.context, o.HintsPatchTournamentsTournamentIDTasksTaskIDHintsHintIDHandler)
	if o.handlers["POST"] == nil {
		o.handlers["POST"] = make(map[string]http.Handler)
	}
	o.handlers["POST"]["/login"] = auth.NewPostLogin(o.context, o.AuthPostLoginHandler)
}

// Serve creates a http handler to serve the API over HTTP
// can be used directly in http.ListenAndServe(":8000", api.Serve(nil))
func (o *TournamentAPI) Serve(builder middleware.Builder) http.Handler {
	o.Init()

	if o.Middleware != nil {
		return o.Middleware(builder)
	}
	if o.useSwaggerUI {
		return o.context.APIHandlerSwaggerUI(builder)
	}
	return o.context.APIHandler(builder)
}

// Init allows you to just initialize the handler cache, you can then recompose the middleware as you see fit
func (o *TournamentAPI) Init() {
	if len(o.handlers) == 0 {
		o.initHandlerCache()
	}
}

// RegisterConsumer allows you to add (or override) a consumer for a media type.
func (o *TournamentAPI) RegisterConsumer(mediaType string, consumer runtime.Consumer) {
	o.customConsumers[mediaType] = consumer
}

// RegisterProducer allows you to add (or override) a producer for a media type.
func (o *TournamentAPI) RegisterProducer(mediaType string, producer runtime.Producer) {
	o.customProducers[mediaType] = producer
}

// AddMiddlewareFor adds a http middleware to existing handler
func (o *TournamentAPI) AddMiddlewareFor(method, path string, builder middleware.Builder) {
	um := strings.ToUpper(method)
	if path == "/" {
		path = ""
	}
	o.Init()
	if h, ok := o.handlers[um][path]; ok {
		o.handlers[um][path] = builder(h)
	}
}
